[package]
name = "examples"
version = "0.1.0"
authors = ["Sam Sieber <swsieber@gmail.com>"]

[dependencies]
derive_builder_sugar = { path = "../derive_builder_sugar"}
derive_params_sugar = { path = "../derive_params_sugar"}
base = { path = "../base"}